Add javascript-task-3
urfu-2018/javascript-task-3 pull request #24
Opened 2018-10-28 17:01 UTC by Ropedann

2018-10-28 17:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 17:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 18:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 18:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 18:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 20:28 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-28 20:28 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-10-30 20:41 UTC, SemyonMakhaev requested changes
🍅 

Привет! Молодец, хорошее решение

2018-10-30 20:41 UTC, SemyonMakhaev commented on robbery.js
> +    let timeGap = getParsRegEx(partGap);
`timeGap` может быть null, нужно предусмотреть этот случай

2018-10-30 20:41 UTC, SemyonMakhaev commented on robbery.js
> +    return { start: start, end: end };
```suggestion
    return { start, end };
```

2018-10-30 20:41 UTC, SemyonMakhaev commented on robbery.js
> +    let banksHours = getFullInterval(workingHours);
Для переменных, значение которых не будет меняться, принято использовать `const`

2018-10-30 20:41 UTC, SemyonMakhaev commented on robbery.js
> +        schedule[person].forEach((interval) => {
`map`

2018-10-30 20:41 UTC, SemyonMakhaev commented on robbery.js
> +    Object.keys(schedule).forEach((person) => {
Когда колбэк принимает один аргумент, скобки можно не указывать

2018-11-11 18:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 18:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 18:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 19:26 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-11 19:26 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-11-12 20:42 UTC, SemyonMakhaev requested changes
🍅 

Почти всё круто

2018-11-12 20:42 UTC, SemyonMakhaev commented on robbery.js
> +    let start = DAYS_WORKS.indexOf(fullInterval.from.day) * (24 * 60) +
Константы 24 и 60 лучше выносить в переменные в начало файла

2018-11-12 20:42 UTC, SemyonMakhaev commented on robbery.js
> +            firstInterval.end > secondInterval.start) ||
Такие условия трудно читать. Нужно вынести небольшие проверки в переменные

2018-11-12 20:42 UTC, SemyonMakhaev commented on robbery.js
> +            return postMoment.length !== 0;
Эта проверка выполняется дважды. Можно вынести в переменную или переместить `return` внутрь условия выше

2018-12-30 10:48 UTC, closed without merging