Калугин Павел
urfu-2018/javascript-task-3 pull request #25
Opened 2018-10-28 18:08 UTC by pk8642

2018-10-28 18:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2018-10-28 18:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-28 18:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2018-10-28 18:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 19:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 19:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 20:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 20:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 20:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 20:20 UTC, pk8642 commented
🔔 где таится зло?

2018-10-28 20:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-28 21:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-29 15:19 UTC, pk8642 commented
Помогите, пожалуйста, дедлайн совсем близко, я что только ни тестил, где-то недоработка, а где - понять не могу 'напуганный взгляд'

2018-10-29 15:25 UTC, ya-woodcutter commented
У вас же еще неделя есть, не боись. В течение часа гляну, разберемся :)

2018-10-29 16:32 UTC, ya-woodcutter commented on robbery.js
> +                gap1.fromInMinutes > gap2.fromInMinutes);
Метод `.sort` не изменяет исходный массив и возвращать функция должна немного другие значения. Правильно будет так:
```
noRobTime[day] = noRobTime[day].sort((gap1, gap2) =>
    gap1.fromInMinutes - gap2.fromInMinutes);
```
Вообще по коду хочу тебя попросить константы отделять пустыми строчками, читать когда все вместе и не отделяется тяжеловато (плюсы в карму и респекты за это, конечно же, полагаются) + заметил, что в переменной `noRobTime` есть интервалы типа `{ from: 1439, to: 1439 }`, что не очень прикольно и бесполезно. Надеюсь помог этим :)

2018-10-29 16:43 UTC, pk8642 commented on robbery.js
> +                gap1.fromInMinutes > gap2.fromInMinutes);
насчет последнего: это вероятнее всего из-за того, что при инициализации массива занятости берется начало дня - начало работы банка и конец работы банка - конец дня, и если банк работает до 23:59, то как раз и появится такой промежуток. Этого можно избежать, написав написав проверку на разницу в 1 минуту, но, мне кажется, если честно, в ней еще меньше смысла, чем в интервале 1439 - 1439 'задумчивость'

2018-10-29 16:44 UTC, pk8642 commented on robbery.js
> +                gap1.fromInMinutes > gap2.fromInMinutes);
константы вообще все разделятьпустыми строчками?

2018-10-29 16:50 UTC, ya-woodcutter commented on robbery.js
> +                gap1.fromInMinutes > gap2.fromInMinutes);
Хорошо отделять блоки констант, например:
```
const a = 10;
const b = 11;
function sum(a, b) {
    return a + b;
}
let c = 0;
if (a > b) {
    c = sum(a, b);
}
```
vs
```
const a = 10;
const b = 11;

function sum(a, b) {
    return a + b;
}

let c = 0;

if (a > b) {
    c = sum(a, b);
}
```

2018-10-29 16:51 UTC, pk8642 commented on robbery.js
> +                gap1.fromInMinutes > gap2.fromInMinutes);
понял, сейчас подправлю

2018-10-29 16:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-29 17:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2018-10-29 17:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 17:03 UTC, honest-hrundel commented
@ya-woodcutter обрати внимание: решено доп. задание

2018-10-29 17:05 UTC, pk8642 commented
пойду читать документацию, спасибо вам большое:)

2018-10-29 17:11 UTC, ya-woodcutter commented
А ну и коммиты советую начинать именовать чуть посерьезнее :) Потому что придумать нормальный текст к коммиту ничуть не легче, чем имя переменной.

2018-10-29 17:12 UTC, ya-woodcutter commented
Не обращай внимания, я не попал по кнопке -_-

2018-10-30 14:21 UTC, ya-woodcutter requested changes
Умеете, могете! 👍

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +const dayEndInMinutes = 1440 - 1;
Такие штуки лучше писать сразу, но добавлять коммент:
`const dayEndInMinutes = 1439 // hoursInDay * minutesInHour - 1`

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +};
Лучше сделать две отдельные переменные: массив с днями и мапу с переводами в индексы.

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +
Лишняя пустая строка

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +
Лишняя пустая строка

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +    const hours = parseInt(timeTable.match(/\d{2}/)[0]);
А если `.match` вернет `null` ? Далее у тебя есть отдельная функция получения таймзоны,  может написать одну, которая бы парсила дату и возвращала `{ day, hours, minutes, timezone }`?

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
>      console.info(schedule, duration, workingHours);
Давай уберем не нужный код :)

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +        if (schedule[robber].length > 0) {
А если `schedule[robber] === undefined`?) Тут, наверное, я слишком придираюсь, но лучше проверять такое. Вообще условием может быть `schedule[robber] && schedule[robber][0]`, тогда мы проверим, чтобы не сломалась строчка ниже.

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +        if (differenceInDays === 0) { // если в 1 день занят, то и добавлять в 1 ключ (ключ = день)
За комменты респект 👍

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +
Зачем пустая строка?)

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +                hours = `0${hours}`;
Добавление 0 можно вынести в отдельный метод и заюзать его для минут и часов.

2018-10-30 14:21 UTC, ya-woodcutter commented on robbery.js
> +                .replace(/%MM/, minutes);
Такие однотипные штуки лучше писать в столбик:
```
return template
    .replace(/%DD/, day)
    .replace(/%HH/, hours)
    .replace(/%MM/, minutes);
```
Так выглядит красиво и консистентно :)

2018-10-30 15:30 UTC, pk8642 commented on robbery.js
> +        if (schedule[robber].length > 0) {
в условии задачи было заверено, что подаваться будут валидные данные

2018-10-30 15:32 UTC, pk8642 commented on robbery.js
>      console.info(schedule, duration, workingHours);
он уже был до меня, сейчас уберу

2018-10-30 15:35 UTC, pk8642 commented on robbery.js
> +    const hours = parseInt(timeTable.match(/\d{2}/)[0]);
в условии было заверено, что подаваться будут валидные данные, функцию сейчас перепишу

2018-10-30 16:04 UTC, pk8642 commented on robbery.js
> +};
а что если сделать просто массив с днями, а индексы находить через `indexOf()`?

2018-10-30 16:44 UTC, pk8642 commented on robbery.js
> +    const hours = parseInt(timeTable.match(/\d{2}/)[0]);
мне таймзона по сути нужна только 1 раз, чтобы посчитать разницу и вычесть из времени, я сейчас немного упрощу код и прокомментирую свой вариант в коде

2018-10-30 16:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 16:58 UTC, honest-hrundel commented
@ya-woodcutter обрати внимание: решено доп. задание

2018-11-06 07:19 UTC, ya-woodcutter approved these changes

2018-11-06 07:19 UTC, ya-woodcutter commented
👍

2018-11-06 07:20 UTC, closed without merging