Черанева Ольга
urfu-2018/javascript-task-3 pull request #32
Opened 2018-10-29 03:32 UTC by OlgaCheraneva

2018-10-29 03:32 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 19

2018-10-29 06:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 19

2018-10-29 07:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 19

2018-10-29 07:32 UTC, OlgaCheraneva commented
🔔

2018-10-30 09:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 10:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 19

2018-10-30 11:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2018-10-30 11:26 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-10-30 11:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 11:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-10-30 11:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 11:44 UTC, honest-hrundel commented
@tonyfresher обрати внимание: решено доп. задание

2018-11-04 17:07 UTC, tonyfresher requested changes
Запозднил с ревью, прости ¯\_(ツ)_/¯

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +};
Логичнее хранить номер дня и количество минут в одном дне. И перемножать их при надобности

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +    const minutesFrom = Number(fromTmp[1]);
А здесь лучше воспользоваться `match` с более понятной и надёжной регуляркой. Можно использовать группы, чтобы удобнее доставать значения:
```javascript
const [fromHours, fromMinutes] = workingHours.from
    .match(/(\d{2}):(\d{2})/)
    .slice(1)
    .map(Number);
```
Обрати внимание, что я делаю `slice(1)`. Потому что первый элемент массива — исходная строка.

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +    const minutesTo = Number(toTmp[1]);
Ну и тут по аналогии

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +            const tmp = daySchedule.from.replace(/[+:]/g, ' ').split(' ');
`tmp` — плохое название переменной, потому что ни о чём не сообщает тому, кто читает код

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +        for (let daySchedule of schedule[member]) {
Ты же не изменяешь `member` и `daySchedule`. Тогда `const`

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +            const tmp = daySchedule.from.replace(/[+:]/g, ' ').split(' ');
И зачем так сложно, если тебе нужно фактически
```suggestion
            const memberTimezone = Number(daySchedule.from.split('+')[1]);
```

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +            const timezoneDiff = (bankTimezone - memberTimezone) * 60;
Ты заметила, что ты тут вычитаешь две строки? В JS это работает, и `'12' - '12' = 0`. Но этим не стоит пренебрегать, потому что тогда ты рискуешь выстрелить себе в ногу и не понимать, что происходит

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +                let startMinute = intersections[0].from;
При создании переменной всегда пиши модификатор 'const'. И только потом, если тебе приходится где-то её переприсвоить меняй на 'let'. Переменные с 'const' более предсказуемые. Ты сразу даёшь тому, кто читает код, понять, что переменная в будущем меняться не будет

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +                const day = dayOfTheWeek[Math.trunc(startMinute / 1440)];
60, 24, 10, 1440... Многовато волшебных цифр. Вынеси в константы, чтобы было понятно, что каждая из них означает

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +            const delay = 30;
Давай вынесем это в глобальные константы, чтобы она не создавалась при каждом выполнении, и переназовём понятнее?

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +function formatBankWorkingHours(workingHours) {
Скорее `paraseWorkingHours`

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +    const tmp = time.replace(/[+:]/g, ' ').split(' ');
Можно не реплэйсить, а сплитить по нескольким делиметрам:
```javascript
const timeParts = time.split(/\s|:|\+/)
```

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +    // let clone = Object.assign([], intersections);
Лишний закомменченный код

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +    // const end = daySchedule.to;
И ещё :-)

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +function changeIntersections(interval, daySchedule) {
А тут лучше `updateIntersections`

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +function filterIntersictions(duration) {
Поставь себе спэлл-чекер, чтобы больше не писать «Inters**i**ctions» :-)

2018-11-04 17:07 UTC, tonyfresher commented on robbery.js
> +function filterIntersictions(duration) {
По названию функции не очень понятно, что она делает. Давай `removeShortIntersections`

2018-11-07 05:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-07 05:58 UTC, honest-hrundel commented
@tonyfresher обрати внимание: решено доп. задание

2018-11-07 06:13 UTC, OlgaCheraneva commented
Исправления отправила, но commint здесь не появился

2018-11-07 19:38 UTC, tonyfresher approved these changes
🍏

2018-11-07 19:38 UTC, tonyfresher commented on robbery.js
> +const minutesFromStart = {
Суть объекта поменялась, а имя переменной нет :-)

2018-11-07 19:38 UTC, tonyfresher commented on robbery.js
> +const minutesInDay = 1440;
Константы базовых типов-значений (Number, String, Boolean) лучше именовать снейк-кейсом в верхнем регистре — `ВОТ_ТАК`

2018-11-07 19:38 UTC, tonyfresher commented on robbery.js
> +                const day = dayOfTheWeek[Math.trunc(startMinute / 1440)];
Ну у тебя же даже переменная теперь есть. Почитай [вики](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования). Если выносишь числа в константы, можешь легко их менять. И самое главное — код становится читаемее и понятнее

2018-11-07 19:38 UTC, tonyfresher commented on robbery.js
> +            const delay = 30;
А-та-та :-)

2018-11-07 19:38 UTC, closed without merging

2018-11-08 05:41 UTC, OlgaCheraneva commented
Почему  closed-after-deadline и half-accepted? Я давно решение отправила, до deadline

2018-11-08 06:03 UTC, tonyfresher commented
Исправления выехали в среду в 11 часов, что фактически позже двухнедельного дедлайна. Нооо.. Я проверял 5 дней — мой факап — поэтому держи accepted :-)

2018-11-08 07:10 UTC, OlgaCheraneva commented
Спасибо