Окуньков Семен
urfu-2018/javascript-task-3 pull request #35
Opened 2018-10-29 10:22 UTC by WisdomSpirit

2018-10-29 10:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2018-10-29 10:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 10:36 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-10-29 16:10 UTC, plotnikovn requested changes

2018-10-29 16:10 UTC, plotnikovn commented on robbery.js
> +    return [['ПН', 'ВТ', 'СР'][day], hours, minutes];
у тебя уже есть описание дней `numericalDayOfTheWeekEnum`, заиспользуй его или поменяй структуру

2018-10-29 16:10 UTC, plotnikovn commented on robbery.js
> +        timeShift = Number(timeParts[3]);
лучше вынести в переменные с явными названиями `timeParts[3]`

2018-10-30 20:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 20:48 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-10-30 20:49 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 20:49 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-10-30 20:55 UTC, closed without merging