Зелинский Дмитрий
urfu-2018/javascript-task-3 pull request #36
Opened 2018-10-29 10:37 UTC by Nerzull3

2018-10-29 10:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 19

2018-10-29 11:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 19

2018-10-29 11:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2018-10-29 11:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 16

2018-10-29 14:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 14:29 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-10-30 21:15 UTC, SemyonMakhaev requested changes
🍅 

Привет! Круто, что декомпозируешь логику на небольшие функции 👍

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +                .replace('%HH', hours > 9 ? hours : '0' + hours)
Можно вынести в функцию и заиспользовать её для форматирования часов и минут

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        for (let i = 0; i < DAYS.length; i++) {
`map`

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        for (let time of schedule[person]) {
`map`

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        let a0 = minTime;
Переменные должны иметь понятное название

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        for (let time of times) {
Здесь можно скомбинировать `filter` и `map`

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        const [a1, b1] = freeTime1;
Давай будем стараться называть переменные со смыслом :)

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +            let temp = time[0];
```suggestion
            let [temp] = time;
```

2018-10-30 21:15 UTC, SemyonMakhaev commented on robbery.js
> +        for (let person of Object.getOwnPropertyNames(schedule)) {
`map`

2018-10-31 02:13 UTC, Nerzull3 commented on robbery.js
> +                .replace('%HH', hours > 9 ? hours : '0' + hours)
У меня так много функций в основном методе, что линтер не дает добавить еще:( Придется убирать какие-то, объединять. Например getDayOfWeek, getHours, getMinutes, getTimeZone. Но так хочется оставить их раздельными. В будущем удобнее использовать

2018-10-31 03:22 UTC, SemyonMakhaev commented on robbery.js
> +                .replace('%HH', hours > 9 ? hours : '0' + hours)
По хорошему нужно те функции, которые не используют `successfulTimes`, вынести за пределы основной функции, а те, которые используют, сделать "приватными" методами возвращаемого объекта. Объявлять новые функции прямо внутри основной функции не эффективно, потому что они будут создаваться в памяти каждый раз при вызове этой функции

2018-10-31 03:43 UTC, Nerzull3 commented on robbery.js
> +                .replace('%HH', hours > 9 ? hours : '0' + hours)
Хорошо, учту это

2018-10-31 07:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-31 07:51 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-11-02 20:11 UTC, SemyonMakhaev approved these changes
🍏 👍

2018-11-02 20:12 UTC, closed without merging