Карцев Ярослав
urfu-2018/javascript-task-3 pull request #42
Opened 2018-10-29 14:18 UTC by KartsevYaroslav

2018-10-29 14:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 19

2018-10-29 14:42 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 19

2018-10-29 14:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 19

2018-10-29 14:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2018-10-29 15:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2018-10-29 15:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2018-10-29 16:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2018-10-29 16:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2018-10-29 19:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2018-10-29 20:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2018-10-29 20:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-10-29 20:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 20:10 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2018-10-29 20:24 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 20:24 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2018-11-08 13:57 UTC, KartsevYaroslav commented
🔔

2018-11-25 17:23 UTC, spt30 requested changes
🍅 Привет! К логике претензий нет, молодец! Есть замечания по кодстайлу небольшие

Дедлайн новый до 3 декабря 16:00

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +    let leftBorder = 0;
`leftEdge` все-таки, наверное, лучше

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +        shift: shift,
можно написать просто `shift,` вместо `shift: shift,`
сейчас так можно

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +function getIntersect(firstSchedule, secondSchedule) {
экономишь на символах))
пиши Intersection

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +    return firstSchedule.map(first => {
если у тебя один return в теле стрелочной функции, можно не писать скобки:
```
return firstSchedule
    .map(first => 
        secondSchedule
            .filter(second => first.to > second.from && first.from < second.to)
            .map(second => ({
                from: Math.max(first.from, second.from),
                to: Math.min(first.to, second.to)
            });
    )
    .reduce((x, y) => x.concat(y));
```

отступ в reduce надо поправить тоже левее

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +    appropriateMoments.push([0, 1, 2].map(x => {
тут тоже для улучшения читабельности:
```
appropriateMoments.push(
    [0, 1, 2].map(x => ({
            from: bankWorkingHours.from + x * MINUTES_IN_DAY,
            to: bankWorkingHours.to + x * MINUTES_IN_DAY
    }));
);
```

2018-11-25 17:23 UTC, spt30 commented on robbery.js
> +            return template.replace(
тут тоже с отступами разберись

2018-12-01 12:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-12-01 12:16 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2018-12-04 14:58 UTC, spt30 commented on robbery.js
> +    appropriateMoments
Еще раз внимательно посмотри на коммент:
пуш на той же строке, а массив, который пушишь на следующей вместе с его методом

2018-12-04 14:59 UTC, spt30 commented
🍏

2018-12-04 14:59 UTC, closed without merging