Пироговский Леонид
urfu-2018/javascript-task-3 pull request #56
Opened 2018-10-29 22:16 UTC by Leoltron

2018-10-29 22:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-29 22:17 UTC, honest-hrundel commented
@ya-woodcutter обрати внимание: решено доп. задание

2018-10-30 14:48 UTC, ya-woodcutter requested changes
👍 Очень круто! За комменты и jsdoc респект! Жду правки :)

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +const weekdaysToDaysOffset = new Map();
Давай уберем кучу set'ов через:
```
const weekdaysToDaysOffset = new Map([
    ['ПН', 0],
    ['ВТ', 1],
    ...
]);
```

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +const timeRegexp = /([^\d\s]{2}) (\d\d):(\d\d)(?:\+(\d))?/;
Вместо `\d\d` можно писать `\d{2}` и для таймзоны лучше указать точное количество цифр (`\d{1,2}`). Ну и первый блок у тебя может отсутствовать (через `?:`, чтобы не использовать конкатенацию `'ПН ' +` для банковского времени). А так супер! 👍

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +}
Наверное можно руками такое написать, вряд ли изменятся дни недели ;)

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +    const robberyDays = ['ПН', 'ВТ', 'СР'];
Лучше вынести это наверх к константам

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +function parseTime(timeString) {
Давай на этом месте напишем парсер, который возвращает объект `{ day, hours, minutes, timezone }`. Его можно будет заюзать для всех времен (грабители и банк). А если нужен Date-объект назовем его `parseTimeInDate` и заюзаем внутри него `parseTime`.

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +function zfill(str, length) {
Некст левел такое засунуть в прототип и вызывать для строки, как `string.zfill(10)` (если вы, конечно, проходили прототипы). Но и так хорошо!

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +                    .toString(), 2))
Лучше не переносить :)

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +            const weekday = daysToWeekdays.get((date.getDay() + 7 - 1) % 7);
Можно сразу +6 написать и в комменте рядом пояснить за это.

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +    const members = ['Danny', 'Rusty', 'Linus'];
Можно перенести к константам наверх, но лучше этот список получать динамически. А то для каждого нового грабителя нужно лезть в код за добавлением.

2018-10-30 14:48 UTC, ya-woodcutter commented on robbery.js
> +            parseTime(day + ' ' + workingHours.to)));
`${day} ${workingHours.to}`?

2018-10-30 19:15 UTC, Leoltron commented on robbery.js
> +const timeRegexp = /([^\d\s]{2}) (\d\d):(\d\d)(?:\+(\d))?/;
`\d\d` короче и читается немного полегче. И если я уберу проверку первого блока, как я буду выставлять день при парсинге?

2018-10-30 19:17 UTC, Leoltron commented on robbery.js
> +}
И все же я предпочитаю сохранять связь в таких случаях, ибо можно по неосмотрительности изменить значение в одном `Map`, но не изменить в другом.

2018-10-31 10:00 UTC, Leoltron commented on robbery.js
> +function zfill(str, length) {
ESLint: String prototype is read only, properties should not be added. (no-extend-native) :(

2018-10-31 10:07 UTC, Leoltron commented on robbery.js
> +                    .toString(), 2))
Хм, не понимаю, почему WebStorm здесь переносит

2018-10-31 10:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-31 10:09 UTC, honest-hrundel commented
@ya-woodcutter обрати внимание: решено доп. задание

2018-10-31 10:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-31 10:12 UTC, honest-hrundel commented
@ya-woodcutter обрати внимание: решено доп. задание

2018-10-31 10:12 UTC, Leoltron commented on robbery.js
> +    const members = ['Danny', 'Rusty', 'Linus'];
Не совсем понял, о чем вы. Я о динамическом получении

2018-11-05 14:45 UTC, Leoltron commented
🔔

2018-11-06 07:25 UTC, ya-woodcutter commented on robbery.js
> +    const members = ['Danny', 'Rusty', 'Linus'];
Можно было получать список грабителей из данных, когда они приходят. Но в условии задачи говорится только о трех этих грабителях, так что ок :)

2018-11-06 07:25 UTC, ya-woodcutter commented on robbery.js
> +function zfill(str, length) {
:( Круто, что попробовал!

2018-11-06 07:26 UTC, ya-woodcutter approved these changes

2018-11-06 07:27 UTC, closed without merging