Карташов Александр
urfu-2018/javascript-task-3 pull request #61
Opened 2018-10-30 07:31 UTC by alexander736b

2018-10-30 07:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 11:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 11:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 12:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 13:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 13:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-31 19:21 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-31 19:21 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-10-31 19:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-31 19:42 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-03 18:54 UTC, dotokoto requested changes

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +        if (hours.length < 2) {
Эта часть повторяется дважды. Можно вынести в функцию

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +            from: convertStringToTime(keys[i] + ' ' + workingHours.from),
Можно использовать template string: 
```
`${keys[i]} ${workingHours.from}`
```

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +        arrayIntervals.push({
Раз делаешь push на каждом шаге, можно `forEach` заменить на `map`. И сразу писать `return intervals.map(...)`

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +        arrayUnsuitableTime.forEach(element => unsuitableTime.push(element));
Заем перекладывать все элементы в другой массив, если можно сразу использовать `arrayUnsuitableTime`?

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +        array.forEach(a => {
Здесь тоже непонятно, зачем из одного массива в другой перекладывать элементы

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +            for (let i = 0; i < intervals.length; i++) {
Функция вышла очень большая, и в ней много действий. Стоит попробовать вынести этот `for` в отдельную функцию

2018-11-03 18:54 UTC, Dotokoto commented on robbery.js
> +            fTime -= 30;
Это число хорошо бы унести в константу

2018-11-04 20:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-04 20:43 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-06 07:50 UTC, Dotokoto commented on robbery.js
> +        if (time.length < 2) {
Можно кстати еще сократить:
```
return time.length < 2 ? `0${time}` : time;
```

2018-11-06 07:51 UTC, Dotokoto commented
Принято

2018-11-06 07:51 UTC, closed without merging