Пешков Евгений
urfu-2018/javascript-task-3 pull request #63
Opened 2018-10-30 08:37 UTC by epeshk

2018-10-30 08:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2018-10-30 08:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2018-10-30 09:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 09:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 09:09 UTC, honest-hrundel commented
@KIlyaA обрати внимание: решено доп. задание

2018-11-02 10:59 UTC, Damirikys commented
@KIlyaA проверяй таску, лентяй

2018-11-03 13:14 UTC, KIlyaA requested changes
🍅 Нужно чуть-чуть поправить, а так всё круто)

2018-11-03 13:14 UTC, KIlyaA commented on robbery.js
> +class Time {
Давай добавим jsdoc ко всем методам класса

2018-11-03 13:14 UTC, KIlyaA commented on robbery.js
> +        if (!(openTime <= timeOfDay && timeOfDay < closeTime)) {
А может лучше раскрыть скобки в логическом выражении?

2018-11-03 13:14 UTC, KIlyaA commented on robbery.js
> +        return busyTimes.every(x => !(x.from <= time && time < x.to));
И здесь может тоже поработать над логическим выражением?

2018-11-03 13:14 UTC, KIlyaA commented on robbery.js
> +    for (let prop in schedule) {
`prop`?

2018-11-06 02:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-06 02:38 UTC, honest-hrundel commented
@KIlyaA обрати внимание: решено доп. задание

2018-11-06 05:04 UTC, KIlyaA approved these changes

2018-11-06 05:05 UTC, KIlyaA commented
🍏

2018-11-06 05:05 UTC, closed without merging