first try
urfu-2018/javascript-task-3 pull request #65
Opened 2018-10-30 08:54 UTC by MaxtiCorn

2018-10-30 08:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-10-30 08:55 UTC, honest-hrundel commented
@Xrias обрати внимание: решено доп. задание

2018-11-02 06:34 UTC, Xrias requested changes
Молодец, константы только повыносить.

2018-11-02 06:34 UTC, Xrias commented on robbery.js
>      console.info(schedule, duration, workingHours);
Надо убрать

2018-11-02 06:34 UTC, Xrias commented on robbery.js
> +        minutesTo: hoursInDay * 7 * minutesInHour - 1
7?

2018-11-02 06:34 UTC, Xrias commented on robbery.js
> +            let minute = (startTime % 60).toString();
60?

2018-11-02 06:34 UTC, Xrias commented on robbery.js
> +            if (factDuration - 30 >= needDuration) {
30?

2018-11-05 16:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-05 16:01 UTC, honest-hrundel commented
@Xrias обрати внимание: решено доп. задание

2018-11-05 17:11 UTC, closed without merging