go
urfu-2018/javascript-task-3 pull request #71
Opened 2018-10-30 09:08 UTC by kutemba0580

2018-10-30 09:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 09:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 10:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-11-25 18:33 UTC, spt30 requested changes
🍅 
Код написан круто, логика хорошая
Есть пара замечаний общих:
1) Разделяй пустыми строками фукнции, константы в начале от функций и так далее. Это улучшить читаемость
2) если у тебя есть такой код:
```
    return {
        day: day,
        hour: hour,
        minute: minute
    };
```
можно его сократить:
`return { day, hour, minute };`
3) много где можно и нужно использовать const вместо let

Респект за то, что числа вынес в константы, молодец!

P.S. новый дедлайн 3 декабря 01:00

2018-11-25 18:33 UTC, spt30 commented on robbery.js
> +    let intersections = [];
ты ссылку на этот массив нигде не изменяешь, можно написать const

2018-11-25 18:33 UTC, spt30 commented on robbery.js
> +    for (let i = 0; i < intervalsForRobbery.length; i++) {
итерироваться по массиву можно встроенными методами

2018-11-29 18:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-11-29 19:34 UTC, spt30 commented
Все еще не поправлены некоторые замечания

2018-11-30 05:20 UTC, kutemba0580 commented
Можно спросить,что именно надо менять? Я не совсем понял

пт, 30 нояб. 2018 г., 0:34 Тощилин Сергей notifications@github.com:

> Все еще не поправлены некоторые замечания
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/urfu-2018/javascript-task-3/pull/71#issuecomment-442964205>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ApmT0RitDJv2Ry3QtStizHjP9lVMM9l-ks5u0DbJgaJpZM4YBeIN>
> .
>

2018-11-30 05:25 UTC, spt30 commented
@kutemba0580 Нужно поправить:
- отбивки функций пустыми строками
- итерирование по массиву с for(i) заменить на встроенные в язык методы
- там, где это допустимо, заменить let на const, это хороший тон

2018-12-15 08:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2018-12-15 16:30 UTC, spt30 commented
🍏

2018-12-15 16:30 UTC, closed without merging