Акишкина Вероника
urfu-2018/javascript-task-3 pull request #82
Opened 2018-11-05 09:40 UTC by AirenLaird

2018-11-05 09:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-05 10:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 11:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-05 11:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 11:59 UTC, AirenLaird commented
🔔

2018-11-05 12:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 16

2018-11-05 12:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 13:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 13:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 13:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-05 13:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 13:48 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 15:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2018-11-05 17:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-05 17:25 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-05 17:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-05 17:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-05 17:37 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-05 17:45 UTC, AirenLaird commented
Заметка для себя: значит была гарантия на то, что интервалы занятости для ребят пересекаться не будут

2018-11-05 17:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-05 18:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-05 18:00 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-05 18:06 UTC, AirenLaird commented
Интересно, почему нет теста на наличие правильного сдвига на пол часа, если это допустимо в том же промежутке..
То есть если задать такой тест:
const gangSchedule = {
    Danny: [
        { from: 'ПН 01:00+5', to: 'ПН 06:30+5' },
        { from: 'ВТ 01:00+5', to: 'ВТ 06:30+5' }
    ],
    Rusty: [
        { from: 'ПН 01:00+5', to: 'ПН 06:30+5' },
        { from: 'ВТ 01:00+5', to: 'ВТ 06:30+5' }
    ],
    Linus: [
        { from: 'ПН 01:00+5', to: 'ПН 06:30+5' },
        { from: 'ВТ 01:00+5', to: 'ВТ 06:30+5' }
    ]
};

const bankWorkingHours = {
    from: '00:00+5',
    to: '08:00+5'
};
время ограбления = 90 минут, то у вас допустим вот такой ответ:
true
Метим на ПН, старт в 06:30!
ВТ 06:30
СР 00:00
СР 00:00
СР 00:00
---
это я проверяла коммитом выше, хотя ответ должен быть такой:
true
Метим на ПН, старт в 06:30!
ВТ 06:30
СР 00:00
СР 00:30
СР 01:00
его я реализовала коммитом ниже

2018-11-05 18:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-05 18:09 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-15 10:08 UTC, dotokoto requested changes

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +    let commonSpareTime = conversionToCommonSpareTime(schedule);
У тебя ведь не меняется значение этой переменной? Тогда лучше использовать `const`. 
Вообще стратегия такая: использовать везде `const`, и менять на `let`, только если значение действительно нужно менять. Во всех остальных местах тоже можешь посмотреть и поставить `const` везде, где можно

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +        if (schedule.hasOwnProperty(key)) {
Чтобы была меньшая вложенность кода, можно писать так:
```
if (!schedule.hasOwnProperty(key)) {
    continue;
}
...
```

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +            spareTime = spareTime.concat(schedule[key].reduce((acc, busyTime) => {
Лучше не писать слишком вложенные функции, иначе код становится труднее понимать. 
Здесь можно вынести результат внутреннего `reduce` в переменную. Тогда по ее названию сразу станет понятней, что происходит. И после уже делать `concat`.

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +    daysToConvert
1) У тебя при каждом вызове `converting` создается этот объект и заполняется одинаковыми значениями. Стоит вынести его в константу и использовать её.
2) А зачем именно `Map`? Кажется, что хватило бы и простого объекта
```
const DAYS_TO_NUMBER = {'ПН': 1, 'ВТ': 2, ...}
```

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +    date.setUTCMonth(9);
Для чего это?

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +function converting(timeStartOrEnd) {
В данной функции ведь неважно, какое именно время? Можно назвать переменную просто `time`

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +    date = date.valueOf() - Number(timezone) * 3600000;
В этой задаче использование `Date` скорее мешает. Сама видишь, сколько дополнительных действий пришлось делать, чтобы нормально с ними работать ) Вообще хорошо, что поразбиралась в методах даты. Но можно было бы просто переводить все значения в миллисекунды, без использования `Date`

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +    date = date.valueOf() - Number(timezone) * 3600000;
3600000 - стоит вынести в константу и явно расписать, как она считается

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +            let DDHHMM = converting2(forTryLater.intervals[0].from);
`converting2` - название не говорит о том, что происходит в функции. И тем более, чем она отличается от просто `converting`. И вообще, если приходится использовать цифры в названиях функций/переменных, значит с ними точно что-то не так )
Попробуй выбрать более подходящее название, из которого будет понятнее, что делает функция

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +            let tempTo = forTryLater.intervals[0].from;
У тебя и там и там взят `.from`, это странно 🤔

2018-11-15 10:08 UTC, dotokoto commented on robbery.js
> +            30 * 60000;
30 и 60000 - константы. Их нужно вынести в начало кода и дать понятные названия

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +            forTryLater.filterAndSorting();
Точно ли нужно каждый раз заново сортировать интервалы? Попробуй переписать так, чтобы они сортировались один раз. А дальше ведь всегда берется следующий интервал, порядок их при этом ломаться не должен

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +        hours = '0' + hours;
Добавление нуля можно вынести в отдельную функцию, оно 2 раза используется

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +    DDHHMM.push(minutes);
А еще, может удобнее было бы использовать тут объект, а не массив

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +            this.intervals.forEach(sorting);
Попробуй переписать так, чтобы использовать стандартную функцию `sort`. В нее можно передавать функцию-правило сортировки

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +    let bank = ['ПН ', 'ВТ ', 'СР '];
Это тоже похоже на константу

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +    bank = bank.map(day => {
Можно короче:
`return bank.map(...)`

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +                    to: robberyInterval.to
Все эти случаи сводятся к 
```
from: max(robberyInterval.from, day.from),
to: min(robberyInterval.to, day.to)
```

2018-11-15 10:08 UTC, Dotokoto commented on robbery.js
> +function secondEveryTimeInCommonTime(time, i, leisureInterval) {
Эти три функции тоже похожи и кажутся избыточными. Может, получится сократить?

2018-11-16 10:46 UTC, AirenLaird commented on robbery.js
> +    daysToConvert
1. Вынесла daysToConvert и daysToConvert2
2. разве простой объект может иметь строку в качестве имени свойства? Это же только Map может иметь в качестве ключа любой тип

2018-11-16 10:52 UTC, AirenLaird commented on robbery.js
> +    date.setUTCMonth(9);
.-.

2018-11-16 10:57 UTC, AirenLaird commented on robbery.js
> +    date = date.valueOf() - Number(timezone) * 3600000;
Я думала, что раз про это рассказали, значит нужно использовать 🙈 поняла

2018-11-16 11:06 UTC, AirenLaird commented on robbery.js
> +    date = date.valueOf() - Number(timezone) * 3600000;
я просто посмотрела сколько в одном часе миллисекунд и умножила на это число :) теперь сделала как надо

2018-11-16 11:12 UTC, AirenLaird commented on robbery.js
> +            let tempTo = forTryLater.intervals[0].from;
😱

2018-11-17 02:40 UTC, AirenLaird commented on robbery.js
> +            forTryLater.filterAndSorting();
У меня просто filter (для выделения промежутка, большего или равного времени ограбления) и sorting (упорядочивание) как две функции в одной были, оставила только фильтрацию как функцию, использую сортировку один раз в функции getAppropriateMoment

2018-11-17 03:21 UTC, AirenLaird commented on robbery.js
> +    DDHHMM.push(minutes);
Возможно, но ведь это не сильно изменит код

2018-11-17 04:20 UTC, AirenLaird commented on robbery.js
> +    let bank = ['ПН ', 'ВТ ', 'СР '];
я почему-то думала, что bank измениться с помощью функции map, поэтому нужен let. То есть писать const, если длина массива не меняется/если не меняется выделенная под массив память?

2018-11-17 04:34 UTC, AirenLaird commented on robbery.js
> +                    to: robberyInterval.to
😰

2018-11-17 06:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2018-11-17 06:12 UTC, honest-hrundel commented
@Dotokoto обрати внимание: решено доп. задание

2018-11-19 06:54 UTC, Dotokoto commented on robbery.js
> +    let bank = ['ПН ', 'ВТ ', 'СР '];
const можно писать, если не меняется ссылка на массив. А удалять и менять там элементы можно

2018-11-23 08:54 UTC, Dotokoto commented on robbery.js
> +    daysToConvert
И то и то можно, никто не запрещает ) Там и есть строки в качестве ключей

2018-11-23 08:56 UTC, Dotokoto commented on robbery.js
> +    DDHHMM.push(minutes);
Читаемость должна улучшиться

2018-11-23 08:57 UTC, Dotokoto commented
Принято

2018-11-23 08:57 UTC, closed without merging